[package]
name = "json_to_csv"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.26"
csv = "1.2.2"
kakasi = "0.1.0"
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.103"
