name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: debian-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy
    - run: cargo fmt -- --check
    - run: cargo clippy --all-targets --all-features -- -D warnings
    - run: cargo test --all-targets --all-features